/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutOrganizerRouteImport } from './routes/about-organizer'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as BookAStandRouteImport } from './routes/book-a-stand'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as RegisterToVisitRouteImport } from './routes/register-to-visit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOrganizerRoute = AboutOrganizerRouteImport.update({
  id: '/about-organizer',
  path: '/about-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAStandRoute = BookAStandRouteImport.update({
  id: '/book-a-stand',
  path: '/book-a-stand',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterToVisitRoute = RegisterToVisitRouteImport.update({
  id: '/register-to-visit',
  path: '/register-to-visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-organizer': typeof AboutOrganizerRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/book-a-stand': typeof BookAStandRoute
  '/contact-us': typeof ContactUsRoute
  '/register-to-visit': typeof RegisterToVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-organizer': typeof AboutOrganizerRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/book-a-stand': typeof BookAStandRoute
  '/contact-us': typeof ContactUsRoute
  '/register-to-visit': typeof RegisterToVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-organizer': typeof AboutOrganizerRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/book-a-stand': typeof BookAStandRoute
  '/contact-us': typeof ContactUsRoute
  '/register-to-visit': typeof RegisterToVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-organizer'
    | '/become-a-partner'
    | '/book-a-stand'
    | '/contact-us'
    | '/register-to-visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-organizer'
    | '/become-a-partner'
    | '/book-a-stand'
    | '/contact-us'
    | '/register-to-visit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-organizer'
    | '/become-a-partner'
    | '/book-a-stand'
    | '/contact-us'
    | '/register-to-visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutOrganizerRoute: typeof AboutOrganizerRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  BookAStandRoute: typeof BookAStandRoute
  ContactUsRoute: typeof ContactUsRoute
  RegisterToVisitRoute: typeof RegisterToVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-organizer': {
      id: '/about-organizer'
      path: '/about-organizer'
      fullPath: '/about-organizer'
      preLoaderRoute: typeof AboutOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-stand': {
      id: '/book-a-stand'
      path: '/book-a-stand'
      fullPath: '/book-a-stand'
      preLoaderRoute: typeof BookAStandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-to-visit': {
      id: '/register-to-visit'
      path: '/register-to-visit'
      fullPath: '/register-to-visit'
      preLoaderRoute: typeof RegisterToVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutOrganizerRoute: AboutOrganizerRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  BookAStandRoute: BookAStandRoute,
  ContactUsRoute: ContactUsRoute,
  RegisterToVisitRoute: RegisterToVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
